# # # # # # # # # # # # # # # # # # # #
# DEVELOPMENT DOCKERFILE              #
# # # # # # # # # # # # # # # # # # # #

version: "3.8"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
  minio_data:

services:
  # # # # # # # # # # # # # # # # # # #
  # APP                               #
  # # # # # # # # # # # # # # # # # # #

  app:
    build:
      context: .
      dockerfile: ./docker/app/dev/Dockerfile
    command: unitd --no-daemon --control 0.0.0.0:8090
    volumes:
      - ./app:/srv/www/app
      - ./server:/srv/www/app/server
    networks:
      default:
        ipv4_address: 172.20.0.10
    environment:
      - APP_URL=${APP_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - CRYPTO_SECRET_SALT=${CRYPTO_SECRET_SALT}
      - CRYPTO_SECRET_KEY=${CRYPTO_SECRET_KEY}
      - USER_TOKEN_EXPIRATION_HOURS=${USER_TOKEN_EXPIRATION_HOURS}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USE_TLS=${SMTP_USE_TLS}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_DISPLAY_NAME=${SMTP_DISPLAY_NAME}
      - SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
      - STORAGE_ACCESS_KEY_ID=${STORAGE_ACCESS_KEY_ID}
      - STORAGE_SECRET_ACCESS_KEY=${STORAGE_SECRET_ACCESS_KEY}
      - STORAGE_DEFAULT_REGION=${STORAGE_DEFAULT_REGION}
      - STORAGE_DEFAULT_BUCKET=${STORAGE_DEFAULT_BUCKET}
      - STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
    ports:
      - 8080:8080 # App
      - 6006:6006 # Storybook
      - 4983:4983 # Drizzle Studio
      - 8090:8090 # Unit config
    depends_on:
      - postgres
      - storage
      - smtp
      # - redis
    restart: on-failure

  # # # # # # # # # # # # # # # # # # #
  # POSTGRES: DATABASE                #
  # # # # # # # # # # # # # # # # # # #

  postgres:
    image: postgres:13.0-alpine
    networks:
      default:
        ipv4_address: 172.20.0.20
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # # # # # # # # # # # # # # # # # # #
  # OBJECT STORAGE: MINIO/S3          #
  # # # # # # # # # # # # # # # # # # #

# # # # # # # # # # # # # # # # # # #
  # OBJECT STORAGE: MINIO/S3          #
  # # # # # # # # # # # # # # # # # # #

  storage:
    image: minio/minio:RELEASE.2024-10-02T17-50-41Z
    networks:
      default:
        ipv4_address: 172.20.0.30
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${STORAGE_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${STORAGE_SECRET_ACCESS_KEY}
      - MINIO_REGION=${STORAGE_DEFAULT_REGION}
      - MINIO_BUCKET=${STORAGE_DEFAULT_BUCKET}
    command: server --address ":9000" --console-address ":9001" /data
    restart: on-failure
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # # # # # # # # # # # # # # # # # # # #
  # # REDIS                             #
  # # # # # # # # # # # # # # # # # # # #

  # redis:
  #   image: redis:7.0-alpine
  #   networks:
  #     default:
  #       ipv4_address: 172.20.0.40
  #   ports:
  #     - 6379:6379
  #   restart: on-failure

  # # # # # # # # # # # # # # # # # # #
  # MAIL: MAILDEV - MOCK SMTP & INBOX #
  # # # # # # # # # # # # # # # # # # #

  smtp:
    image: maildev/maildev
    networks:
      default:
        ipv4_address: 172.20.0.50
    ports:
      - 1080:1080
      - 1025:1025
